### ISSUE TITLE
Peer to Peer Code Review Morning Session

### ISSUE THREAD

**Issue by Jawad-Nazari** [Cisco-the-wayword/To-do-list#7]
**Hi  @Cisco-the-wayword ,**

- Well done. Great work. Your code is well-written and organized. It follows good practices like importing modules, using descriptive variable names and separating concerns into functions. However, there is a  suggestion that could be considered to improve the code:

- Instead of disabling ESLint rules at the beginning of the file, it is better to configure ESLint properly to match the project's requirements.

**Comment by Cisco-the-wayword** [comment]
Thank you very much for pointing it out.
I have reviewed it and made the necessary configurations
